import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import { useFeatures } from "@packages/firebase/hooks";
import type { Features } from "@packages/firebase/contexts";
import { getFeatures } from "@packages/firebase/utils";

import styles from "../styles/Home.module.css";

export interface HomeServerSideProps {
  features?: Features;
}

const Home: NextPage = () => {
  const features = useFeatures();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>{`${JSON.stringify(features)}`}</p>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<
  HomeServerSideProps
> = async () => {
  try {
    const features = await getFeatures<Features>();
    return { props: { features } };
  } catch (e) {
    return { props: {} };
  }
};

export default Home;
